language: csharp
mono: none
dotnet: 2.0.0
env:
  global:
    - NUGETURL=https://api.nuget.org/v3/index.json
    - VERSION=${TRAVIS_TAG:-0.0.0-dev}
    - PRODUCT=QRest
    - AUTHORS='QRest Contributors'
script:
  - echo $VERSION
  - dotnet restore ./QueryableRest/
  - dotnet build ./QueryableRest/ -c Release -p:Version=$VERSION -p:InformationalVersion=$VERSION:$TRAVIS_COMMIT -p:Product=$PRODUCT -p:Authors=$AUTHORS
  - dotnet test ./QueryableRest/test/QRest.Semantics.MethodChain.Tests -c Release --no-build
deploy:
  skip_cleanup: true
  provider: script
  script: |
      dotnet pack ./QueryableRest/ -c Release --no-build -p:Version=$VERSION -p:Product=$PRODUCT -p:Authors=$AUTHORS && \
      dotnet nuget push .\QueryableRest\src\QRest.AspNetCore\*.nupkg -s $NUGETURL -k $NUGETKEY && \
      dotnet nuget push .\QueryableRest\src\QRest.Core\*.nupkg -s $NUGETURL -k $NUGETKEY && \
      dotnet nuget push .\QueryableRest\src\QRest.QRest.Semantics.MethodChain\*.nupkg -s $NUGETURL -k $NUGETKEY
  on:
    tags: true
